### ISSUE TITLE
Not getting response from Website. Maybe the base url is wrong?

### ISSUE THREAD

**Issue by rawhsetig** [rameezarshad/naukri-api#1]
**System**: Mac
**python**: 3.11.5

I get no response error `requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)` after executing the script. 

The base url when I checked is not found on browser. Is it correct url? _'https://www.nma.mobi'_

I get below error while running the script.
```Traceback (most recent call last):
  File "/Users/giteshwarmali/anaconda3/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/giteshwarmali/anaconda3/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/giteshwarmali/anaconda3/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/giteshwarmali/anaconda3/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/giteshwarmali/Documents/naukri-api/naukri.py", line 239, in <module>
    main()
  File "/Users/giteshwarmali/Documents/naukri-api/naukri.py", line 220, in main
    if not user_info or not naukri.valLogin(*user_info):
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/giteshwarmali/Documents/naukri-api/naukri.py", line 98, in valLogin
    if login_response.json().get('error'):
       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/giteshwarmali/anaconda3/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)```

**Comment by michael-hedi** [comment]
Ill get the fork of this repo and see what will be the issue :  ) ~ !!!

**Comment by michael-hedi** [comment]
https://github.com/rameezarshad/naukri-api/pull/2
@rameezarshad 

can you verify this PR and Approve
